#pragma once
#include <cstdint>

namespace Blam::Game
{
	enum class MedalType : uint8_t
	{
		Exterminations,
		Perfections,
		DoubleKills,
		TripleKills,
		OverKills,
		Killtaculars,
		Killtrocities,
		Killimanjaros,
		Killtastrophes,
		Killpocalypses,
		Killionaires,
		KillingSprees,
		KillingFrenzies,
		RunningRiots,
		Rampages,
		Untouchables,
		Invincibles,
		SniperSprees,
		Sharpshooters,
		ShotgunSprees,
		OpenSeasons,
		SplatterSprees,
		VehicularManslaughters,
		SwordSprees,
		SliceNDices,
		JuggernautSprees,
		Unstoppables,
		InfectionSprees,
		MMMBrains,
		ZombieKillingSprees,
		HellsJanitors,
		Unknown1,
		HailToTheKings,
		Bulltrue,
		Splatters,
		HiJacks,
		Skyjacks,
		KillsFromTheGrave,
		Killjoys,
		LaserKills,
		Sticks,
		Headshots,
		Assasinations,
		Beatdowns,
		Incinerations,
		Wheelmans,
		BombPlanteds,
		KilledBombCarriers,
		KilledVIPs,
		KilledJuggernauts,
		OddballKills,
		FlagScores,
		KilledFlagCarriers,

		Count
	};
}