#pragma once
#include <cstdint>

namespace AnvilEldorado::Blam::Input
{
	enum class KeyCode : uint16_t
	{
		eKeyCodeEscape,
		eKeyCodeF1,
		eKeyCodeF2,
		eKeyCodeF3,
		eKeyCodeF4,
		eKeyCodeF5,
		eKeyCodeF6,
		eKeyCodeF7,
		eKeyCodeF8,
		eKeyCodeF9,
		eKeyCodeF10,
		eKeyCodeF11,
		eKeyCodeF12,
		eKeyCodePrintScreen,
		eKeyCodeF14,
		eKeyCodeF15,
		eKeyCodeTilde, // VK_OEM_3
		eKeyCode1,
		eKeyCode2,
		eKeyCode3,
		eKeyCode4,
		eKeyCode5,
		eKeyCode6,
		eKeyCode7,
		eKeyCode8,
		eKeyCode9,
		eKeyCode0,
		eKeyCodeMinus,
		eKeyCodePlus,
		eKeyCodeBack,
		eKeyCodeTab,
		eKeyCodeQ,
		eKeyCodeW,
		eKeyCodeE,
		eKeyCodeR,
		eKeyCodeT,
		eKeyCodeY,
		eKeyCodeU,
		eKeyCodeI,
		eKeyCodeO,
		eKeyCodeP,
		eKeyCodeLBracket, // VK_OEM_4
		eKeyCodeRBracket, // VK_OEM_6
		eKeyCodePipe, // VK_OEM_5
		eKeyCodeCapital,
		eKeyCodeA,
		eKeyCodeS,
		eKeyCodeD,
		eKeyCodeF,
		eKeyCodeG,
		eKeyCodeH,
		eKeyCodeJ,
		eKeyCodeK,
		eKeyCodeL,
		eKeyCodeColon, // VK_OEM_1
		eKeyCodeQuote, // VK_OEM_7
		eKeyCodeEnter,
		eKeyCodeLShift,
		eKeyCodeZ,
		eKeyCodeX,
		eKeyCodeC,
		eKeyCodeV,
		eKeyCodeB,
		eKeyCodeN,
		eKeyCodeM,
		eKeyCodeComma,
		eKeyCodePeriod,
		eKeyCodeQuestion, // VK_OEM_2
		eKeyCodeRShift,
		eKeyCodeLControl,
		eKeyCodeUnused46, // Left Windows key, but will always fail
		eKeyCodeLAlt,
		eKeyCodeSpace,
		eKeyCodeRAlt,
		eKeyCodeUnused4A, // Right Windows key, but will always fail
		eKeyCodeApps,
		eKeyCodeRcontrol,
		eKeyCodeUp,
		eKeyCodeDown,
		eKeyCodeLeft,
		eKeyCodeRight,
		eKeyCodeInsert,
		eKeyCodeHome,
		eKeyCodePageUp,
		eKeyCodeDelete,
		eKeyCodeEnd,
		eKeyCodePageDown,
		eKeyCodeNumLock,
		eKeyCodeDivide,
		eKeyCodeMultiply,
		eKeyCodeNumpad0,
		eKeyCodeNumpad1,
		eKeyCodeNumpad2,
		eKeyCodeNumpad3,
		eKeyCodeNumpad4,
		eKeyCodeNumpad5,
		eKeyCodeNumpad6,
		eKeyCodeNumpad7,
		eKeyCodeNumpad8,
		eKeyCodeNumpad9,
		eKeyCodeSubtract,
		eKeyCodeAdd,
		eKeyCodeNumpadEnter,
		eKeyCodeDecimal,
		eKeyCodeUnused68,
		eKeyCodeShift,
		eKeyCodeCtrl,
		eKeyCodeUnused6B, // Windows key, but will always fail
		eKeyCodeAlt,

		eKeyCode_Count,
		eKeyCode_None = 0xFF, // An invalid key code (for use in unset bindings)
	};
}